name = input('what is your name ?')
name = ('jaseam')
print('Hello'+ name)
age = input('how old you are')
print('Whoa,' + age + 'years old... I was born today.')
feeling = input('good')
print('How are you feeling today?' + feeling + 'Glad to know you are feeling good. That is wonderful to hear')
response = input('not at all!')
print ('are you excited for school?' + response + 'well have a good day!!')